drop database gcommunity;
create database gcommunity;
SHOW DATABASES;
use gcommunity;

#사용자 테이블	생성
CREATE TABLE `USER_TB` (
	`USER_NUMBER`	INT	NOT null AUTO_INCREMENT PRIMARY KEY,				#회원번호
	`USER_ID`	VARCHAR(20)	NOT NULL,										#아이디
	`USER_PW`	VARCHAR(20)	NOT NULL,										#비밀번호
	`USER_NAME`	VARCHAR(20)	NOT NULL,										#이름
	`USER_NICKNAME`	VARCHAR(20)	NOT NULL,									#닉네임
	`USER_GENDER`	VARCHAR(20)	NOT NULL,									#성별
	`USER_DOB`	VARCHAR(20)	NOT NULL,										#생년월일
	`USER_EMAIL`	VARCHAR(30)	NOT NULL,									#이메일
	`USER_PHONENUMBER`	VARCHAR(20)	NOT NULL,								#휴대전화
	`USER_JOINDATE`		DATETIME	NOT NULL	DEFAULT NOW(),				#가입일
	`USER_SECESSIONDATE`	DATETIME	NULL,								#탈퇴일
	`USER_AUTHORITY`	INT	NOT NULL	COMMENT '0 : 관리자 1 : 유저',			#권한
	`USER_STATE`	INT	NOT NULL	COMMENT '0 : 탈퇴   1 : 활동중   2: 정지'	#활동상태
);

#게시판 테이블생성
CREATE TABLE `BOARD_TB` (
	`BOARD_NUMBER`	INT	NOT null AUTO_INCREMENT PRIMARY KEY,				#게시판번호
	`BOARD_NAME`	VARCHAR(20)	NOT NULL,									#게시판이름
	`BOARD_INPUTDATE`	DATETIME	NOT NULL	DEFAULT NOW(),				#게시판등록일
	`BOARD_CORRENT`	DATETIME	NULL,										#게시판수정일
	`BOARD_DELETEDATE`	DATETIME	NULL,									#게시판삭제일
	`BOARD_MANAGER`	INT	NOT NULL											#게시판생성자
);

#게시글 테이블생성
CREATE TABLE `POST_TB` (
	`POST_NUMBER`	INT	NOT null AUTO_INCREMENT PRIMARY KEY,				#게시글번호
	`BOARD_NUMBER`	INT	NOT NULL,											#게시판번호
	`POST_TITLE`	VARCHAR(100)	NOT NULL,								#제목
	`POST_CONTENTS`	VARCHAR(1000)	NOT NULL,								#내용
	`POST_CATEGORY`	VARCHAR(20)	NOT NULL,									#카테고리
	`POST_INPUTDATE`	DATETIME	NOT NULL	DEFAULT NOW(),				#작성일
	`POST_CORRENT`	DATETIME	NULL,										#수정일
	`POST_DELETEDATE`	DATETIME	NULL,									#삭제일
	`POST_RECOMMEND`	INT	NOT NULL	DEFAULT 0,							#추천수
	`POST_VIEWS`	INT	NOT NULL	DEFAULT 0,								#조회수
	`POST_WRITER`	INT	NOT NULL											#작성자
);

#댓글 테이블생성
CREATE TABLE `COMMENT_TB` (
	`COMMENT_NUMBER`	INT	NOT null AUTO_INCREMENT PRIMARY KEY,			#댓글번호
	`BOARD_NUMBER`	INT	NOT NULL,											#게시판번호
	`POST_NUMBER`	INT	NOT null,											#게시글번호
	`COMMENT_CONTENTS`	VARCHAR(1000)	NOT NULL,							#댓글내용
	`COMMENT_INPUTDATE`	DATETIME	NOT NULL	DEFAULT NOW(),				#댓글등록일
	`COMMENT_CORRENT`	DATETIME	NULL,									#댓을수정일
	`COMMENT_DELETEDATE`	DATETIME	NULL,								#댓글삭제일
	`COMMENT_RECOMMEND`	INT	NOT NULL	DEFAULT 0,							#댓글추천수
	`COMMENT_WRITER`	INT	NOT NULL										#댓글작성자
);

#파일첨부 테이블생성
CREATE TABLE `ATTACHMENTS_TB` (
	`FILE_NUMBER`	INT	NOT null AUTO_INCREMENT PRIMARY KEY,				#파일번호
	`BOARD_NUMBER`	INT	NOT NULL,											#게시판번호
	`POST_NUMBER`	INT	NOT NULL,											#게시글번호
	`FILE_NAME`	VARCHAR(20)	NOT NULL,										#파일이름
	`FILE_SIZE`	DOUBLE	NOT NULL,											#파일사이즈
	`FILE_EXTENSION`	VARCHAR(20)	NOT NULL,								#파일확장자
	`FILE_INPUTDATE`	DATETIME	NOT NULL	DEFAULT NOW(),				#파일등록일
	`FILE_DELETEDATE`	DATETIME	NULL									#파일삭제일
);

ALTER TABLE `POST_TB` ADD CONSTRAINT `FK_BOARD_TB_TO_POST_TB_1` FOREIGN KEY (
	`BOARD_NUMBER`
)
REFERENCES `BOARD_TB` (
	`BOARD_NUMBER`
);
ALTER TABLE `POST_TB` ADD CONSTRAINT `FK_USER_TB_TO_POST_TB_1` FOREIGN KEY (
	`POST_WRITER`
)
REFERENCES `USER_TB` (
	`USER_NUMBER`
);
ALTER TABLE `COMMENT_TB` ADD CONSTRAINT `FK_POST_TB_TO_COMMENT_TB_1` FOREIGN KEY (
	`POST_NUMBER`
)
REFERENCES `POST_TB` (
	`POST_NUMBER`
);
ALTER TABLE `COMMENT_TB` ADD CONSTRAINT `FK_POST_TB_TO_COMMENT_TB_2` FOREIGN KEY (
	`BOARD_NUMBER`
)
REFERENCES `POST_TB` (
	`BOARD_NUMBER`
);
ALTER TABLE `COMMENT_TB` ADD CONSTRAINT `FK_USER_TB_TO_COMMENT_TB_1` FOREIGN KEY (
	`COMMENT_WRITER`
)
REFERENCES `USER_TB` (
	`USER_NUMBER`
);
ALTER TABLE `BOARD_TB` ADD CONSTRAINT `FK_USER_TB_TO_BOARD_TB_1` FOREIGN KEY (
	`BOARD_MANAGER`
)
REFERENCES `USER_TB` (
	`USER_NUMBER`
);
ALTER TABLE `ATTACHMENTS_TB` ADD CONSTRAINT `FK_POST_TB_TO_ATTACHMENTS_TB_1` FOREIGN KEY (
	`POST_NUMBER`
)
REFERENCES `POST_TB` (
	`POST_NUMBER`
);
ALTER TABLE `ATTACHMENTS_TB` ADD CONSTRAINT `FK_POST_TB_TO_ATTACHMENTS_TB_2` FOREIGN KEY (
	`BOARD_NUMBER`
)
REFERENCES `POST_TB` (
	`BOARD_NUMBER`
);

#게시판 데이터삽입
insert into `BOARD_TB` (
	`BOARD_NUMBER`,			#게시판번호
	`BOARD_NAME`,			#게시판이름
	`BOARD_INPUTDATE`,		#게시판등록일
	`BOARD_CORRENT`,		#게시판수정일
	`BOARD_DELETEDATE`,		#게시판삭제일
	`BOARD_MANAGER`			#게시판생성자
)values
	(null,'자유게시판',default,null,null,1),
	(null,'팁/공략',default,null,null,1),
	(null,'공지사항',default,null,null,1)
;