/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-21 17:03:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- 화면 최적화 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width-device-width\", initial-scale=\"1\">\r\n");
      out.write("<!-- 루트 폴더에 부트스트랩을 참조하는 링크 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar navbar-default\"> <!-- 네비게이션 -->\r\n");
      out.write("        <div class=\"navbar-header\">     <!-- 네비게이션 상단 부분 -->\r\n");
      out.write("            <!-- 네비게이션 상단 박스 영역 -->\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("                data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("                aria-expanded=\"false\">\r\n");
      out.write("                <!-- 이 삼줄 버튼은 화면이 좁아지면 우측에 나타난다 -->\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <!-- 상단 바에 제목이 나타나고 클릭하면 main 페이지로 이동한다 -->\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"main.jsp\">Gcommunity</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 게시판 제목 이름 옆에 나타나는 메뉴 영역 -->\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li><a href=\"main.jsp\">게시판</a></li>\r\n");
      out.write("                <li><a href=\"bbs.jsp\">추천글</a></li>\r\n");
      out.write("                <li><a href=\"bbs.jsp\">팁/공략</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- 헤더 우측에 나타나는 드랍다운 영역 -->\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("                        data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("                        aria-expanded=\"false\">접속하기<span class=\"caret\"></span></a>\r\n");
      out.write("                    <!-- 드랍다운 아이템 영역 -->    \r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li class=\"active\"><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("                        <li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 회원가입 양식 -->\r\n");
      out.write("    <div class=\"container\">     <!-- 하나의 영역 생성 -->\r\n");
      out.write("        <div class=\"col-lg-4\">  <!-- 영역 크기 -->\r\n");
      out.write("            <!-- 점보트론은 특정 컨텐츠, 정보를 두드러지게 하기 위한 큰 박스 -->\r\n");
      out.write("            <div class=\"jumbotron\" style=\"padding-top: 20px;\">\r\n");
      out.write("                <form method=\"post\" action=\"joinAction.jsp\" onsubmit=\"return checkPassFunction();\"> <!-- form 태그 ation은 뭐냐면 보낸다고 폼태그안에 입력된 정보를 post 방식으로 -->\r\n");
      out.write("                    <h3 style=\"text-align: center;\">회원가입 화면</h3>\r\n");
      out.write("                    \r\n");
      out.write("                    <h5 style=\"text-align: left;\">아이디</h5>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        \r\n");
      out.write("	                        <input type=\"text\" class=\"form-control\" placeholder=\"10자 이내로 씁시다..\"\r\n");
      out.write("	                         id=\"user_ID\" name=\"user_ID\" maxlength=\"10\" onkeyup=\"idCheckReturn();\">\r\n");
      out.write("	                        <input type=\"button\" onclick=\"idCheckFunction();\" value=\"중복체크\">\r\n");
      out.write("	                        	                        \r\n");
      out.write("	                        <!-- <button onclick=\"action='./idCheckAction.jsp';\">중복체크</button> -->\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <h5 style=\"text-align: left;\">비밀번호</h5>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" placeholder=\"영문,숫자 포함 8자 이상 16자 이내\" onkeyup=\"passwordCheckFunction();\" \r\n");
      out.write("                        id=\"user_PW1\" name=\"user_PW\" maxlength=\"20\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                   <h5 style=\"text-align: left;\">비밀번호 확인</h5>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" placeholder=\"영문,숫자 포함 8자 이상 16자 이내\" onkeyup=\"passwordCheckFunction();\" \r\n");
      out.write("                        id=\"user_PW2\" name=\"user_PW\" maxlength=\"20\">\r\n");
      out.write("                        <h5 style=\"color: red;\" id=\"passwordCheckMessage\"></h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                   <!--  <tr>\r\n");
      out.write("                    <td style=\"text-align: Left\" colspan=\"3\"><h5 style=\"color: red;\" id=\"passwordCheckMessage\"></h5></td>\r\n");
      out.write("                    </tr> -->\r\n");
      out.write("                    \r\n");
      out.write("                    <h5 style=\"text-align: left;\">이름</h5>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"한글 또는 영문 8자 이내\" name=\"user_Name\" maxlength=\"20\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <h5 style=\"text-align: left;\">닉네임</h5>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"한글 또는 영문 8자 이내\" \r\n");
      out.write("                        id=\"user_NickName\" name=\"user_NickName\" maxlength=\"20\" onkeyup=\"nickCheckReturn();\">\r\n");
      out.write("                        <input type=\"button\" onclick=\"nickCheckFunction();\" value=\"중복체크\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <h5 style=\"text-align: left;\">생년월일</h5>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"생년월일8자리\" name=\"user_DOB\" maxlength=\"20\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\" style=\"text-align: center;\">\r\n");
      out.write("                        <div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("                            <label class=\"btn btn-primary active\">\r\n");
      out.write("                                <input type=\"radio\" name=\"user_Gender\" autocomplete=\"off\" value=\"남자\" checked>남자\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"btn btn-primary active\">\r\n");
      out.write("                                <input type=\"radio\" name=\"user_Gender\" autocomplete=\"off\" value=\"여자\" checked>여자\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <h5 style=\"text-align: left;\">이메일</h5>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" placeholder=\"이메일\" \r\n");
      out.write("                        id=\"user_Email\" name=\"user_Email\" maxlength=\"20\" onkeyup=\"emailCheckReturn();\">\r\n");
      out.write("                        <input type=\"button\" onclick=\"emailCheckFunction();\" value=\"중복체크\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <h5 style=\"text-align: left;\">휴대전화</h5>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"전화번호입력 - 빼고\" \r\n");
      out.write("                        name=\"user_PhoneNumber\" id=\"user_PhoneNumber\" maxlength=\"20\">\r\n");
      out.write("                        <input type=\"button\" onclick=\"CertifiedNumberCheck();\" value=\"인증번호 받기\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <input type=\"submit\" class=\"btn btn-primary form-control\" value=\"회원가입\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>  \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 부트스트랩 참조 영역 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    var idCheckPass = false;        //아이디중복 체크 확인변수\r\n");
      out.write("    var nickCheckPass = false;      //닉네임중복 체크 확인변수\r\n");
      out.write("    var emailCheckPass = false;     //이메일중복 체크 확인변수\r\n");
      out.write("    var allCheckPass = false;       //위 중복체크변수들 마지막 확인변수\r\n");
      out.write("    /* 아이디 중복 체크 펑션 */\r\n");
      out.write("    function idCheckFunction(){\r\n");
      out.write("       \r\n");
      out.write("        var user_ID = $('#user_ID').val();\r\n");
      out.write("        if(user_ID == null || user_ID == \"\"){\r\n");
      out.write("	         alert(\"아이디를 적어주세요\");\r\n");
      out.write("         }else{\r\n");
      out.write("        	 $.ajax({\r\n");
      out.write("                 type: 'post', url: './UserIdCheck', data:{user_ID: user_ID},\r\n");
      out.write("              success: function(result){\r\n");
      out.write("                  if(result == 1){\r\n");
      out.write("                      alert(\"아이디가 중복입니다\");\r\n");
      out.write("                  }else{\r\n");
      out.write("                      alert(\"아이디 사용 가능합니다\");\r\n");
      out.write("                      \r\n");
      out.write("                      idCheckPass = true;\r\n");
      out.write("                  }\r\n");
      out.write("              }\r\n");
      out.write("             });\r\n");
      out.write("         }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* 닉네임 중복 체크 펑션 */\r\n");
      out.write("    function nickCheckFunction(){\r\n");
      out.write("       \r\n");
      out.write("        var user_NickName = $('#user_NickName').val();\r\n");
      out.write("        if(user_NickName == null || user_NickName == \"\"){\r\n");
      out.write("             alert(\"닉네임을 적어주세요\");\r\n");
      out.write("         }else{\r\n");
      out.write("             $.ajax({\r\n");
      out.write("                 type: 'post', url: './UserNickCheck', data:{user_NickName: user_NickName},\r\n");
      out.write("              success: function(result){\r\n");
      out.write("                  if(result == 1){\r\n");
      out.write("                      alert(\"닉네임을 중복입니다\");\r\n");
      out.write("                  }else{\r\n");
      out.write("                      alert(\"닉네임 사용 가능합니다\");\r\n");
      out.write("                      \r\n");
      out.write("                      nickCheckPass = true;\r\n");
      out.write("                  }\r\n");
      out.write("              }\r\n");
      out.write("             });\r\n");
      out.write("         }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* 이메일 중복 체크 펑션 */\r\n");
      out.write("    function emailCheckFunction(){\r\n");
      out.write("       \r\n");
      out.write("        var user_Email = $('#user_Email').val();\r\n");
      out.write("        if(user_Email == null || user_Email == \"\"){\r\n");
      out.write("             alert(\"이메일을 적어주세요\");\r\n");
      out.write("         }else{\r\n");
      out.write("             $.ajax({\r\n");
      out.write("                 type: 'post', url: './UserEmailCheck', data:{user_Email: user_Email},\r\n");
      out.write("              success: function(result){\r\n");
      out.write("                  if(result == 1){\r\n");
      out.write("                      alert(\"이메일 중복입니다\");\r\n");
      out.write("                  }else{\r\n");
      out.write("                      alert(\"이메일 사용 가능합니다\");\r\n");
      out.write("                      \r\n");
      out.write("                      emailCheckPass = true;\r\n");
      out.write("                  }\r\n");
      out.write("              }\r\n");
      out.write("             });\r\n");
      out.write("         }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function passwordCheckFunction(){    	//그뭐지 비밀번호 와 비밀번호확인이 같은지 \r\n");
      out.write("    	var user_PW1 = $('#user_PW1').val();\r\n");
      out.write("    	var user_PW2 = $('#user_PW2').val();\r\n");
      out.write("    	if(user_PW1 != user_PW2){ //비밀번호와 비밀번호확인이 같지 않다면 \r\n");
      out.write("    		$('#passwordCheckMessage').html('비밀번호가 서로 다릅니다');\r\n");
      out.write("    	}else{\r\n");
      out.write("    		$('#passwordCheckMessage').html('');\r\n");
      out.write("    	}\r\n");
      out.write("    }\r\n");
      out.write("    /* 중복체크 눌러서 확인 받았는지 체크하는 펑션 */\r\n");
      out.write("    \r\n");
      out.write("    function checkPassFunction(){\r\n");
      out.write("        if(idCheckPass == true && nickCheckPass == true && emailCheckPass == true){\r\n");
      out.write("        	return true;\r\n");
      out.write("        }else if(idCheckPass == false){\r\n");
      out.write("    		alert(\"아이디 중복 확인해야합니다.\");\r\n");
      out.write("    		return false;\r\n");
      out.write("    	}else if(nickCheckPass == false){\r\n");
      out.write("            alert(\"닉네임 중복 확인해야합니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }else if(emailCheckPass == false){\r\n");
      out.write("            alert(\"이메일 중복 확인해야합니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("    	\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write(" /*    var idCheckPass = false;        //아이디중복 체크 확인변수\r\n");
      out.write("    var nickCheckPass = false;      //닉네임중복 체크 확인변수\r\n");
      out.write("    var emailCheckPass = false;     //이메일중복 체크 확인변수 */\r\n");
      out.write("    \r\n");
      out.write("  /*  중복확인 값을 다시 적거나 고쳤을경우 다시 중복확인하게끔 */\r\n");
      out.write("   function idCheckReturn(){\r\n");
      out.write("	   idCheckPass = false;\r\n");
      out.write("    }\r\n");
      out.write("   function nickCheckReturn(){\r\n");
      out.write("	   nickCheckPass = false;\r\n");
      out.write("    }\r\n");
      out.write("   function emailCheckReturn(){\r\n");
      out.write("	   emailCheckPass = false;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
